org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1

minecraft_version_range=[1.21.1]

neo_version=21.1.221
loader_version_range=[1,)

mapping_channel=official

mapping_version=1.21.1

mod_id=mobeffectsvfx
mod_name=MobEffectsVFX
mod_license=GPL-3.0
mod_version=1.0-rc

mod_group_id=com.github.darksonic300
mod_authors=darksonic300
mod_description=A client-side mod that adds simple 3D VFX on effect gain! (Server-side installation is still recommended for better functionality)

curseforge_project_id=1382352
modrinth_project_id=lq1wGfHO
