org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1

minecraft_version_range=[1.21.1]

neo_version=21.1.221
loader_version_range=[1,)

mapping_channel=official

mapping_version=1.21.1

mod_id=mob_effects_vfx
mod_name=MobEffectsVFX
mod_license=All Rights Reserved
mod_version=0.8

mod_group_id=com.github.darksonic300
mod_authors=darksonic300
mod_description=Client-side mod that adds simple 3D VFX on effect gain!
