org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]

neo_version=26.1.2.109

mapping_channel=official

mapping_version=1.21.1

mod_id=mobeffectsvfx
mod_name=MobEffectsVFX
mod_license=LGPL-3.0-or-later
mod_version=1.0

mod_group_id=com.github.darksonic300
mod_authors=darksonic300
mod_description=A client-side mod that adds simple 3D VFX on effect gain! (Server-side installation is still recommended for better functionality)

curseforge_project_id=1382352
modrinth_project_id=lq1wGfHO
